### ISSUE TITLE
Runtime configuration not supported anymore 

### ISSUE THREAD

**Issue by Hugoz** [paypal/sdk-core-java#53]
Release 1.6.7 breaks our integration, which had been working fine since 1.1
Root cause is "Resource 'sdk_config.properties' could not be found"

We use merchantsdk which includes the "LATEST" paypal-core. We use runtime configuration: we do not have any sdk_config.properties, because we are a software provider for many merchants. Their credentials are populated at runtime. 

Stack trace:
```
Caused by: java.lang.ExceptionInInitializerError
        at com.paypal.core.DefaultHttpConnection.<init>(DefaultHttpConnection.java:35)
        at com.paypal.core.ConnectionManager.getConnection(ConnectionManager.java:52)
        at com.paypal.core.APIService.makeRequestUsing(APIService.java:152)
        at com.paypal.core.BaseService.call(BaseService.java:265)
        at urn.ebay.api.PayPalAPI.PayPalAPIInterfaceServiceService.doDirectPayment(PayPalAPIInterfaceServiceService.java:2415)
        at urn.ebay.api.PayPalAPI.PayPalAPIInterfaceServiceService.doDirectPayment(PayPalAPIInterfaceServiceService.java:2367)
        ... 105 more
Caused by: java.lang.RuntimeException: java.io.IOException: Resource 'sdk_config.properties' could not be found
        at com.paypal.core.ConfigManager.<init>(ConfigManager.java:91)
        at com.paypal.core.ConfigManager.getInstance(ConfigManager.java:103)
        at com.paypal.core.SSLUtil.<clinit>(SSLUtil.java:43)
        ... 140 more
Caused by: java.io.IOException: Resource 'sdk_config.properties' could not be found
        at com.paypal.sdk.util.ResourceLoader.getInputStream(ResourceLoader.java:50)
        at com.paypal.core.ConfigManager.<init>(ConfigManager.java:86)
        ... 142 more
```

**Comment by tankchintan** [comment]
This has been happening to us as well. Although ours is a new implementation.

**Comment by tankchintan** [comment]
I think this is happening because 22 days ago a commit was made, which called `ConfigManager.getInstance()` which in turn calls the sdk_config.properties file. see [here](https://github.com/paypal/sdk-core-java/commit/6707fd7368667229514919e8153bb208e050c1d8#diff-97794ffb609f7b240bb84f53ed596ce0R43)

**Comment by jaypatel512** [comment]
We are able to reproduce this issue, and are going to make a fix really really soon. I will update you soon.
